### PR TITLE
fixed memory leaks in filewatch_free; fixed msvc compilation errors due to gotos; fixed wrong notification entry bug in filewatch_update; fixed copy paste bug in filewatch_update which caused remounting to fail; fixed tinyfilewatch from not submitting events for all subfiles within a directory that has been removed

### PR DESCRIPTION
**Pull request by dseyedm**

### CODE REVIEW

**Comment by dseyedm** [comment]
shout-out to https://github.com/nothings/stb/blob/master/stb_leakcheck.h

**Comment by dseyedm** [comment]
reproduce the wrong notification entry bug in filewatch_update:

start with the following directory structure:
data/
data/New Folder
data/image.png

Add a single watch on the data/ folder.

Delete data/New Folder

Observe tinyfilewatch submit an erroneous notification regarding the removal of data/image.png

**Comment by RandyGaul** [comment]
This looks great! I’m away for the weekend but I will take a look soon.

**Comment by RandyGaul** [comment]
These all looked solid. I'll merge them now and try them out. Will increment version count and add you as contributor next time I push an update.

**Pull request merged**
